# Generated by Django 3.1.5 on 2021-01-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=300)),
                ('nazwisko', models.CharField(max_length=300)),
                ('numer_pracownika', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=300)),
                ('nazwisko', models.CharField(max_length=300)),
                ('PESEL', models.IntegerField(unique=True)),
                ('adres', models.CharField(max_length=1000)),
                ('data_urodzin', models.DateField()),
            ],
            options={
                'ordering': ('PESEL',),
            },
        ),
        migrations.CreateModel(
            name='RodzajWniosku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=400, unique=True)),
            ],
            options={
                'ordering': ('typ',),
            },
        ),
        migrations.CreateModel(
            name='Wniosek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzasadnienie', models.CharField(max_length=3000)),
                ('Data_zlozenia', models.DateTimeField(auto_now_add=True)),
                ('numer_wniosku', models.IntegerField(unique=True)),
                ('typ_wniosku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wnioski', to='Myapplication.rodzajwniosku')),
            ],
            options={
                'ordering': ('numer_wniosku',),
            },
        ),
    ]
