# Generated by Django 3.1.5 on 2021-02-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0002_wniosek_skladajacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wniosek',
            name='skladajacy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wnioski', to='Myapplication.klient'),
        ),
    ]
